name: Aztec Connect
description: "Aztec Connect is an open source layer 2 network that aims to bring scalability and privacy to Ethereum. It strives to enable affordable, private crypto payments via zero-knowledge proofs. Additionally it allows to deposit funds into a variety of DeFi Protocols such as LiDo, Element.Fi, etc."
bridges:
- address: 0xFF1F2B4ADb9dF6FC8eAFecDcbF96A2B351680455
  tokens:
  - ETH
  - DAI
  - wstETH
nonNativeBridges: []