name: "dYdX"
description: "dYdX aims to build a powerful and professional exchange for trading crypto assets where users can truly own their trades and, eventually, the exchange itself."
tokens: "DYDX"
bridges:
- address: 0xD54f502e184B6B739d7D27a6410a67dc462D69c8
  tokens:
  - USDC
nonNativeBridges: []