name: "Immutable X"
description: "Immutable X claims to be the first Layer 2 for NFTs on Ethereum. It promises zero gas fees, instant trades and scalability for games, applications, marketplaces, without compromise."
tokens:
- IMX
bridges:
- address: 0x5FDCCA53617f4d2b9134B29090C87D01058e27e9
  tokens:
  - IMX
  - ETH
  - USDC
nonNativeBridges: []