name: "Layer2.Finance"
description: "Layer2.Finance aims to democratize access to DeFi protocols for everyone. Users can aggregate their DeFi usage and save on Ethereum fees."
bridges:
- address: 0xf86FD6735f88d5b6aa709B357AD5Be22CEDf1A05
  tokens:
  - BUSD
  - DAI
  - USDC
  - USDT
  - WETH
nonNativeBridges: []