name: "StarkNet"
description: "StarkNet is a general purpose ZK-Rollup built using STARK cryptographic proof system. StarkNet uses the Cairo programming language both for its infrastructure and for writing StarkNet contracts. L2 <--> L1 messaging infrastructure is available and contracts are fully composable. It is currently launched with a single Sequencer."
bridges:
- address: 0xae0Ee0A63A2cE6BaeEFFE56e7714FB4EFE48D419
  tokens:
  - ETH
- address: 0x0437465dfb5B79726e35F08559B0cBea55bb585C
  tokens:
  - DAI
- address: 0x283751A21eafBFcD52297820D27C1f1963D9b5b4
  tokens:
  - WBTC
- address: 0xF6080D9fbEEbcd44D89aFfBFd42F098cbFf92816
  tokens:
  - USDC
- address: 0xbb3400F107804DFB482565FF1Ec8D8aE66747605
  tokens:
  - USDC
nonNativeBridges: []