name: Arbitrum One
description: "Arbitrum is an Optimistic Rollup that aims to feel exactly like interacting with Ethereum, but with transactions costing a fraction of what they do on L1."
bridges:
- address: 0x8315177aB297bA92A06054cE80a67Ed4DBd7ed3a
  tokens:
  - ETH
- address: 0x011B6E24FfB0B5f5fCc564cf4183C5BBBc96D515
  tokens: 
  - ETH
- address: 0xA10c7CE4b876998858b1a9E12b10092229539400
  tokens: 
  - DAI
- address: 0xcEe284F754E854890e311e3280b767F80797180d
  tokens:  []
- address: 0xa3A7B6F88361F48403514059F1F16C8E78d60EeC
  tokens: []
nonNativeBridges: []