name: Aztec
description: "Aztec is an open source layer 2 network that aims to bring scalability and privacy to Ethereum. It strives to enable affordable, private crypto payments via zero-knowledge proofs."
bridges:
- address: 0x737901bea3eeb88459df9ef1BE8fF3Ae1B42A2ba
  tokens:
  - ETH
  - DAI
  - renBTC
  - USDT
nonNativeBridges: []