name: "Polygon Hermez"
description: Hermez is an open-source ZK-Rollup that aims to be optimized for secure, low-cost and usable token transfers on the wings of Ethereum."
bridges:
- address: 0xA68D85dF56E733A06443306A095646317B5Fa633
  tokens: []
nonNativeBridges: []