name: "Arbitrum Nova"
description: "Arbitrum Nova is an AnyTrust chain that aims for ultra low transaction fees. Nova differs from Arbitrum One by not posting transaction data on chain, but to Data Availability Committee."
bridges:
- address: 0xC1Ebd02f738644983b6C4B2d440b8e77DdE276Bd
  tokens:
  - ETH
- address: 0xA2e996f0cb33575FA0E36e8f62fCd4a9b897aAd3
  tokens:
  - DAI
- address: 0xB2535b988dcE19f9D71dfB22dB6da744aCac21bf
  tokens: []
nonNativeBridges: []