name: "OMG Network"
description: "OMG Network claims to be the leading value transfer network for ETH and ERC20 tokens. Using the OMG Network, individuals and businesses can transact on a financial infrastructure that is claimed to be several times faster, 1/3rd the cost, and as secure as the Ethereum Network — while retaining full autonomy over their funds and keys. The Network scales by centralizing transaction processing and remains safe by decentralizing security."
tokens:
- OMG
bridges:
- address: 0x3Eed23eA148D356a72CA695DBCe2fceb40a32ce0
  tokens:
  - ETH
- address: 0x070cB1270A4B2bA53c81CeF89d0FD584Ed4F430B
  tokens: []
nonNativeBridges: []