name: "ZKSwap 1.0"
description: "ZKSwap is a fork of ZkSync with added AMM functionality. Based on ZK-Rollup technology, ZKSwap aims to execute the full functionality of Uniswap on Layer 2, while ensuring the core value of decentralized exchange. ZKSwap aims to increase the TPS by multiple orders of magnitude compared to Uniswap, and make transaction processing hardly consume any gas fees."
bridges:
- address: 0x8ECa806Aecc86CE90Da803b080Ca4E3A9b8097ad
  tokens: []
nonNativeBridges: []